### PR TITLE
Add acceptance testing

### LINKED ISSUE #26: Add acceptance testing to verify behavior
I was thinking about making some automated tests to verify that autoscrolling works in an expected, consistent way across the examples.

Do you have any preferred tools? If not I was going to use Nightwatch + Mocha.

### PR DESCRIPTION
**Pull request by benthemonkey**
Here is a first draft of the automation tests. Will close #26.

At the moment you are required to run `runExamples.sh` before you run the tests, as I couldn't find a clean solution to stopping the example meteor processes without killing every meteor process currently running.

Steps to run the tests:

``` shell
./runExamples.sh
cd ../.. # (go back to the root of the project)
npm install
npm test
```

The last step of the iron-router tests should fail (as mentioned in the html of "Step 8"), as a way of verifying that the tests work as expected. Let me know how you would like me to proceed.

### CODE REVIEW

**Comment by pauldowman** [comment]
I just checked it out, nice! A couple of comments:
1. Could we check if it's iron router and not run the broken one? I think it's a good principle to just see all green and not have to double-check that the failing one _should_ actually be failing. You said "as a way of verifying that the tests work as expected" but I'm not sure what you mean by that.
2. Could you update the readme with instructions, including installing ChromeDriver and putting it in your path? https://github.com/nightwatchjs/nightwatch/wiki/Chrome-Setup
3. The script leaves the meteor/node processes running. Here's a suggestion to fix it:

``` bash
#!/bin/bash

# Exit if any command returns error status
set -e

# Kill background node processes when script exits
trap 'kill $(jobs -p)' EXIT

# just running in a subshell with () would be nicer but seems to mess with trap
run () {
  pushd $1 > /dev/null
  $2 &
  popd > /dev/null
}

run examples/iron-router-example/ "meteor --port 3120"
run examples/flow-router-example/ "meteor --port 4160"

npm test
```

This makes it actually run the tests too, and then exit and kill the node processes when the tests are done. (I'd rename it to test.sh or something). What do you think?

**Comment by benthemonkey** [comment]
1. Allow me to clarify. I didn't intend for the failing test to be merged in. It was simply a sanity check that both of our environments see the same failing test. I've fixed this now.
2. Oops, I forgot about chromedriver being a required step. I want to avoid any setup being required, so I'm using the `selenium-standalone` npm package to install chromedriver automatically.
3. That script is perfect! I modified the last line to run nightwatch instead of `npm test`.

See what you think of my modifications.

One question: I use ES6 in the automation test files, which requires special flags for lower versions of Node. Should I mention a minimum required Node version to run the tests, or simply downgrade my code to ES5?

**Comment by benthemonkey** [comment]
Also, am I correct in understanding that the example apps don't use the local version of router-autoscroll, but rather the latest published version?

**Comment by pauldowman** [comment]
Cool! I'd just mention the minimum node version.

And the example apps have a `packages` directory with a symlink to the root so they use the version that's in this repo. E.g. https://github.com/okgrow/router-autoscroll/tree/master/examples/iron-router-example/packages 

(I just noticed that the non-router version is missing that, which is a bug.)

**Comment by benthemonkey** [comment]
@pauldowman added a version message

**Comment by rgould** [comment]
@benthemonkey I just tried running the test suite on this branch, and I got some failing tests. Here are the results: https://gist.github.com/rgould/2720ba8762b4501851c1

It's not obvious to me as to what is going on at first glance

**Comment by benthemonkey** [comment]
Hi @rgould, I'm not completely sure why the problem was occurring, but on a hunch I tried changing the `getScrollTop` function -- that gets injected and executed on the browser -- from an ES6 arrow function into a normal function. It seems to have fixed the error for me.

**Comment by rgould** [comment]
@benthemonkey Thanks! That did it :)

**Comment by pauldowman** [comment]
So awesome. Thank you @benthemonkey!

**Pull request merged**
