### PR TITLE
Make jQuery optional

### LINKED ISSUE #19: Get rid of jquery
As of Meteor 1.2 jquery is removable. If it's done, your package throws an error as it has dependency on jquery. Sadly it is not defined as requirement in package.

I suggest to remove jquery at all. No need to load bulky lib for simple tasks easily achievable without it.

### PR DESCRIPTION
**Pull request by benthemonkey**
Fixes #19 

I tested this branch with the examples by forcing the `Package["jquery"]` checks to return false. Otherwise jQuery gets used because all of the examples depend on jQuery indirectly.

Let me know what you think.

### CODE REVIEW

**Comment by pauldowman** [comment]
Thanks! Looks good, will test and merge ASAP.

**Comment by pauldowman** [comment]
Weird, I'm getting an error because `Package["jquery"]` is not undefined. `$` is undefined though. Some package in the sample app must be transitively depending on jquery. Maybe it's safer to check `$`?

**Comment by benthemonkey** [comment]
Ah, yes I was able to reproduce. I think one of the packages within the sample app is calling `jQuery.noConflict()` because `$` is undefined but `jQuery` is defined.

At the top of `client/router-autoscroll.js` I'll check for `Package["jquery"]` and, if found, assign `Package["jquery"].jQuery` to a local variable.

**Comment by benthemonkey** [comment]
My changes weren't working with jquery disabled because of issues related to DOM being ready, so I added an additional `Meteor.defer` in `scheduleScroll`

**Comment by karldanninger** [comment]
Eek! @benthemonkey this is neat! Thanks for doing this. Sorry it took so long to get merged in. I reviewed & tested various browsers. Looks good to merge. I'll bump the version

**Pull request merged**
